### ISSUE TITLE
Mission ausmisten

### ISSUE THREAD

**Issue by ghost** [TaskForce47/BMR_Insurgency.Altis#15]
- [x] BTC Scripts raus

- [x] CAS Script raus

- [x] Air Drop Script raus

- [x] Respawn Script raus

- [x] MHQ Script deaktivieren
